name: Trace Files

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start file tracer
        run: |
           sudo apt-get update
           sudo apt-get upgrade libc6
           sudo apt-get upgrade libstdc++6
           chmod +x ./file_tracer && sudo ./file_tracer > file_traces.txt &
      - name: Checkout thundra-demo-todo-app-java repo
        uses: actions/checkout@v2
        with:
          repository: serkan-ozal/thundra-demo-todo-app-java
          path: thundra-demo-todo-app-java          
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven 
        run: |
          mvn clean install
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-result-report
          path: target/surefire-reports/
      - uses: actions/upload-artifact@v3
        with:
          name: file_traces
          path: |
            file_traces.txt
